name: taiwan_superzzle
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  auto_route: ^8.2.0
  shared_preferences: ^2.2.3
  flutter_animate: ^4.5.0
  freezed_annotation: ^2.4.2
  json_annotation: ^4.9.0
  flip_card: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.9
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10
  auto_route_generator: ^8.0.0
  freezed: ^2.5.2
  json_serializable: ^6.8.0


flutter:
  uses-material-design: true